#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCCxpM3zSTbfmSyurxz4gYNwPkfLY2edPCSGVuox+ZihZ3hEKe69EfQmAc8hhchj4cZYmYQVN9Ra7kdE9ZwhwL0rKg0VHpW7ZE5uX5lKYIlCQSzLh4zNTBI2Y2A/8GNtOkDYZOHbUmoHjGBFEMJMluGjYLWOUJ6680mcGdoRD46RcbcdNqmq38iE5EzJ+UDV5ogb6K5zhJ70+yllP5XimUi1mbVCXKspMqO+L2BDtfRASpoLV7wteEhSK0SU8lkXPfBRsOABtPVzwFXjYRUqeothPIJZ0flODiZYLV/uNyehOhiNrY86RBoYRlwHCgBUqCet35lPNSDycWieFzde7IF aws-key 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCz/wpWmsCxaQyuNFrIachc/q9nUdByoUcBcicl/wnKLFktKp6du9np9Uhmo4M0tVHNnWCt5uNEi2ks/0XEbg2J+4heuAAKEDr/TVbgabiWGclYKpEWZvmw8gsQwfpAKVG4aS2re7wB2uhw82ZqzJVpGm3ne+sNnz5uVrxN8HUnuR2OWJD6bA9l/fBmE6zdObVXgrCJGjZmVyB5GMeTDJKExgoBpLggZn9CNdu7Sx989xtNLehu6SWM+mGCq9Lcu7usiPG+SuEb8XynYaCOnv8+Oko6SYeJ9Omq/E7Eg6vZHqCbBQ81TIZrGKcikLmF2xP7EOprGOSPVewke7ak7vvmOI+p/RfIAyXj1+GYny+esk9G+qDRFXP9uiIlMfH1oGkQkztvSDMH+EOHqgY66NWQJPj83CaWH/euR0MROHXjm1ar3RuN9qcASAnzCOQQ1FMwFkpIV5x0NDRx0Zp1rLt8ZUFykmIuHZI4g9u6RdAiuWUxx9/eF0fXZa6Ju7GEMKeMtZxJJjmB/WCOylbkT+NPw5RcxgyRLKmUAicnYKXBmULY3pQM/Ui8KiCyJqRbLDBAR+XZYsZ7X5uhcuteu8KIfA2xEbInB4Q3c0DnnSih+GEC4pEbz+NOfeCpLJEn4gfyV1S9S08sG62ls8NPFociA9aWmE1oXfcqwvOkkYhxOw== aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - apache2
  - libapache2-mod-php

write_files:
  - path: /var/www/html/image.php
    content: |
      <?php
      $ihrname = "Sasa Acimovic";
      ?>

      <html>
        <head>
          <title><?php echo $ihrname; ?></title>
        </head>
        <body>
          Ziege auf einem Hügel.<br />
          <img src="https://sasa-acimovic-bucket.s3.us-east-1.amazonaws.com/ziegeaufberg.jpgZSRvKTEUeDtiqwAoSmaaVJPlazClnuwNND3QW5WWh88EJlZE1LoSkdqBIz7xauWNGV8ykT6ZwLq8oi2GwP6zE6t13pGmUGgMz1WIcAgNCRgNCAWueT%2ByezTP71%2F30A07s2s%2B%2Bfr%2BzOvomOZvhHzn39AD8CcrYtFfAH%2FwxG8m35nYhBJYqfnZIt%2BYq%2BcEr8HL6KL%2B4y3YMw7doiiyqfCpW1GrVqgFIO%2BhuC0OMWBkSRDsCWYsXaEOWgi0FdWPi4LHqOUmUSJy8dd1UFVoR2QI9g4j%2Be%2Byjv9B3YjKkcY9OjZsGHicmZdFUOVw0F7BKKrBzTJXkJ82H5wFG6pI7dZCURQ%2B3QVX2vX%2FwwqLm4qgY6hgJEx22ZMWyer7xpkv2Sr45FY8q8u2dHJWGdbtCapG5ELIl%2Bh46xa1Rx5lVqT7ElxiV3ACMS55W8%2BI%2FiCKq9kzv20jN5Js0eMAoDztYjzj40Gpve57men%2Bck%2FiV5%2B9g0IX88Yaer65dFLJW8yc0PfjbjihST1dAtR4dY74VpPiytbAXvn44AVMkEt9GmhwQcuYP0PTFJECQbpABd%2Fj2O5AudKdhKc7GkwBWtC26SwztKlcO7qey9E7qjk2WjD7OonfBQ546C9pcnrumFyLyGntmMbqkU3BSxYcl6qphtNo5WGCqDeA%2F7AhvzqVpBS5YZzTy5lwVN1KD2kJEeauRUkmY4IkkTUGsi&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231110T144141Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIA53ATMJJKSTTU7YHM%2F20231110%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=1a86947651b8d22115a1d7c3dc3a33b17da360daa9e579e9ed529bce8ecf6538" />

          Bild von unsplash
          <img src="https://images.unsplash.com/photo-1682687221073-53ad74c2cad7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" />
          
        </body>
      </html>

runcmd:
  - sudo systemctl restart apache2