#cloud-config

users: # Liste der Benutzer, die erstellt oder konfiguriert werden sollen
  - name: ubuntu   # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL     # Uneingeschränkter Zugang zum sudo-Kommando, ohne Passwort
    groups: users, admin     # Benutzer zu den Gruppen "users" und "admin" hinzufügen
    home: /home/ubuntu     # Home-Verzeichnis für den Benutzer festlegen
    shell: /bin/bash     # Shell für den Benutzer festlegen
    ssh_authorized_keys:     # Liste der SSH-Schlüssel, die für diesen Benutzer autorisiert sind
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD


ssh_pwauth: false # SSH-Passwortauthentifizierung deaktivieren

disable_root: false # Root-Zugang nicht deaktivieren

package_update: true # Aktualisiert die Paketdatenbank und alle installierten Pakete

packages: # Liste der zu installierenden Pakete
  - curl  # Installiert das 'curl'-Paket
  - wget  # Installiert das 'wget'-Paket